
version: '3.7'

services:

  nginx:
    depends_on:
      - custom
    image: cyberdojo/nginx
    init: true
    container_name: test-nginx
    ports: [ "80:80" ]
    user: root
    
  custom:
    build:
      context: .
      args: [ SHA, PORT ]
    depends_on:
      - custom-start-points
      - saver
    image: cyberdojo/custom
    init: true
    container_name: test-custom
    environment: [ NO_PROMETHEUS ]
    ports: [ "4536:4536" ]
    user: nobody
    read_only: true
    restart: "no"
    tmpfs: [ "/tmp:exec,mode=1777" ] # Sticky bit must be set on /tmp otherwise
                                     # Dir.mktmpdir(id,'/tmp') complains
  custom-start-points:
    user: nobody
    image: ${CYBER_DOJO_CUSTOM}
    init: true
    container_name: test-custom-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "4526:4526" ]
    tmpfs: /tmp
    restart: 'no'

  saver:
    user: saver
    image: cyberdojo/saver:${CYBER_DOJO_SAVER_TAG}
    init: true
    container_name: test-saver
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "4537:4537" ]
    restart: 'no'
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533
