
# This is augmented with dependent services by
# sh/augmented_docker_compose.sh

version: '3.7'

services:

  nginx:
    build:
      context: src/nginx_stub
    container_name: test-nginx
    image: cyberdojo/nginx_custom_stub
    init: true
    ports: [ "80:80" ]
    user: root

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  client:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CUSTOM_CHOOSER_CLIENT_PORT ]
      context: src/client
    depends_on:
      - custom-chooser
      - selenium
    image: cyberdojo/test-custom-chooser-client
    init: true
    ports: [ "${CYBER_DOJO_CUSTOM_CHOOSER_CLIENT_PORT}:${CYBER_DOJO_CUSTOM_CHOOSER_CLIENT_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody
    volumes: [ "./test:/test/:ro" ]

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  custom-chooser:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CUSTOM_CHOOSER_PORT ]
      context: src/server
    depends_on:
      - custom-start-points
      - creator
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_CUSTOM_CHOOSER_IMAGE}
    init: true
    ports: [ "${CYBER_DOJO_CUSTOM_CHOOSER_PORT}:${CYBER_DOJO_CUSTOM_CHOOSER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody
    volumes: [ "./test:/test/:ro" ]

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  selenium:
    image: selenium/standalone-firefox
    ports: [ "4444:4444" ]
