
version: '3.7'

services:

  custom-server:
    build:
      context: .
      args: [ SHA, PORT ]
    depends_on:
      - custom-start-points
    image: cyberdojo/custom
    init: true
    container_name: test-custom-server
    environment: [ NO_PROMETHEUS ]
    ports: [ "4536:4536" ]
    user: nobody
    read_only: true
    restart: "no"

  custom-start-points:
    user: nobody
    image: ${CYBER_DOJO_CUSTOM}
    init: true
    container_name: test-custom-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "4526:4526" ]
    tmpfs: /tmp
    restart: 'no'
